export const adsData = [
  {
    title: 'Beautiful Apartment in Nauplion',
    type: 'RENT',
    area: 'Nauplion',
    placeId: 'ChIJv8AB6wrwnxQREGm64iy9AAU',
    price: 1000,
    level: 1,
    bathrooms: 2,
    description:
      'A stunning apartment in the heart of Nauplion with a view of the sea.',
  },
  {
    title: 'Cozy Cottage in Aliveri',
    type: 'BUY',
    area: 'Aliveri',
    placeId: 'ChIJZby5b_pdoRQR-KOdR3vV00E',
    price: 150000,
    level: 0,
    bathrooms: 1,
    description:
      'A charming cottage in the serene town of Aliveri, perfect for nature lovers.',
  },
  {
    title: 'Spacious Apartment in Ioannina',
    type: 'RENT',
    area: 'Ioannina',
    placeId: 'ChIJZ93-3qLpWxMRwJe54iy9AAQ',
    price: 1200,
    level: 2,
    bathrooms: 2,
    description:
      'A spacious apartment with a great view of the city in Ioannina.',
  },
  {
    title: 'Modern Apartment in Chalkida',
    type: 'BUY',
    area: 'Chalkida',
    placeId: 'ChIJSxfWwksWoRQRBMk0e18KCzg',
    price: 180000,
    level: 1,
    bathrooms: 2,
    description:
      'A modern apartment in the heart of Chalkida, close to amenities.',
  },
  {
    title: 'Luxurious Penthouse in Patras',
    type: 'BUY',
    area: 'Patras',
    placeId: 'ChIJLe0kpZk1XhMRoIy54iy9AAQ',
    price: 300000,
    level: 3,
    bathrooms: 3,
    description: 'A luxurious penthouse with panoramic views of Patras.',
  },
  {
    title: 'Seaside Villa in Χανιά',
    type: 'BUY',
    area: 'Χανιά',
    placeId: 'ChIJOz_P4L59nBQRqCzNeX1Vs5Q',
    price: 250000,
    level: 1,
    bathrooms: 2,
    description:
      'A beautiful seaside villa in Χανιά with direct access to the beach.',
  },
  {
    title: 'Cozy Apartment in Ikaria',
    type: 'RENT',
    area: 'Ikaria',
    placeId: 'ChIJNYPCIJ7ivBQRbY6epQI16Jc',
    price: 800,
    level: 0,
    bathrooms: 1,
    description: 'A cozy apartment in the picturesque island of Ikaria.',
  },
  {
    title: 'Mountain Retreat in Loutraki',
    type: 'EXCHANGE',
    area: 'Loutraki',
    placeId: 'ChIJXzpprEYVoBQR7BKcEmrHxxg',
    price: 0,
    level: -1,
    bathrooms: 1,
    description: 'A peaceful mountain retreat in the outskirts of Loutraki.',
  },
  {
    title: 'Seaside Retreat in Skopelos',
    type: 'RENT',
    area: 'Skopelos',
    placeId: 'ChIJpZT5i5HqphQR4TPHTsAzneM',
    price: 1200,
    level: 0,
    bathrooms: 2,
    description: 'A charming seaside retreat on the island of Skopelos.',
  },
  {
    title: 'Modern Apartment in Peristeri',
    type: 'BUY',
    area: 'Peristeri',
    placeId: 'ChIJTazECEejoRQRYRYsuxSJ348',
    price: 200000,
    level: 1,
    bathrooms: 2,
    description: 'A modern apartment in the vibrant suburb of Peristeri.',
  },
];
